package com.hsystems.lms.common;

/**
 * Created by naungsoe on 17/9/16.
 */
public enum Permission {

  VIEW_RESOURCE,
  EDIT_RESOURCE,
  VIEW_HOME,
  VIEW_ASSIGNMENTS,
  VIEW_QUESTIONS,
  CREATE_QUESTION,
  VIEW_QUIZS,
  CREATE_QUIZ,
  ATTEMPT_QUIZ,
  VIEW_LESSON_PACKAGES,
  CREATE_LESSON_PACKAGE,
  ATTEMPT_LESSON_PACKAGE,
  VIEW_STORAGE,
  UPLOAD_FILE,
  VIEW_USERS,
  CREATE_USER,
  VIEW_GROUPS,
  CREATE_GROUP
}
