package com.hsystems.lms.common;

/**
 * Created by naungsoe on 17/9/16.
 */
public enum Permission {

  VIEW_RESOURCE,
  CREATE_RESOURCE,
  VIEW_HOME,
  VIEW_ASSIGNMENTS,
  EDIT_ASSIGNMENT,
  VIEW_QUESTIONS,
  EDIT_QUESTION,
  VIEW_QUIZZES,
  EDIT_QUIZ,
  VIEW_LESSON_PACKAGES,
  EDIT_LESSON_PACKAGE,
  VIEW_STORAGE,
  EDIT_FILE,
  VIEW_USERS,
  EDIT_USER,
  VIEW_GROUPS,
  EDIT_GROUP
}
